# Generated by Django 3.2.7 on 2021-10-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('views', models.IntegerField(verbose_name='number of impressions')),
                ('clicks', models.IntegerField(verbose_name='number of faces')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='cost')),
                ('date_add', models.DateField(auto_now_add=True, verbose_name='date create')),
            ],
        ),
    ]
