# Generated by Django 3.2.7 on 2021-12-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='cost',
            field=models.IntegerField(verbose_name='cost'),
        ),
    ]
