# Generated by Django 3.2.7 on 2021-12-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_alter_statistics_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='cpc',
            field=models.IntegerField(default=34, verbose_name='cpc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='cpm',
            field=models.IntegerField(default=23, verbose_name='cpm'),
            preserve_default=False,
        ),
    ]
