# Generated by Django 3.2.7 on 2021-12-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_auto_20211215_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='cpc',
            field=models.IntegerField(blank=True, null=True, verbose_name='cpc'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='cpm',
            field=models.IntegerField(blank=True, null=True, verbose_name='cpm'),
        ),
    ]
